services:
  - type: web
    name: wallet-shop
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DATA_DIR
        value: /var/data
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: RATE_URL
        sync: false
      - key: RATE_PATH
        sync: false
      - key: RATE_SEC
        value: "10"
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: TG_SESSION
        sync: false
